version: "3.9"

services:
  auth-db:
    image: postgres:15
    container_name: fotofilo-auth-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data

  user-db:
    image: postgres:15
    container_name: fotofilo-user-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: user_db
    volumes:
      - user_data:/var/lib/postgresql/data

  product-db:
    image: postgres:15
    container_name: fotofilo-product-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
    volumes:
      - product_data:/var/lib/postgresql/data

  order-db:
    image: postgres:15
    container_name: fotofilo-order-db
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    volumes:
      - order_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:15
    container_name: fotofilo-payment-db
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db
    volumes:
      - payment_data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:15
    container_name: fotofilo-inventory-db
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    volumes:
      - inventory_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:15
    container_name: fotofilo-notification-db
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
      POSTGRES_DB: notification_db
    volumes:
      - notification_data:/var/lib/postgresql/data

  cart-db:
    image: postgres:15
    container_name: fotofilo-cart-db
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_pass
      POSTGRES_DB: cart_db
    volumes:
      - cart_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fotofilo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: fotofilo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fotofilo-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    restart: always
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: fotofilo-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  auth_data:
  user_data:
  product_data:
  order_data:
  payment_data:
  inventory_data:
  notification_data:
  cart_data:
  redis_data:
  es_data:
